// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package secretstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SecretStore struct {
	Key       string           `json:"key"`
	Value     []byte           `json:"value"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}
