// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package secretstore

import (
	"context"
)

type Querier interface {
	GetSecretStore(ctx context.Context, key string) (SecretStore, error)
	UpsertSecretStore(ctx context.Context, arg UpsertSecretStoreParams) error
}

var _ Querier = (*Queries)(nil)
