// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package shared

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 外部账户表，对齐 trigger.dev ExternalAccount 模型
type ExternalAccounts struct {
	ID pgtype.UUID `json:"id"`
	// 外部账户标识符，在环境内唯一
	Identifier string `json:"identifier"`
	// 外部账户元数据 JSON
	Metadata       []byte             `json:"metadata"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Organizations struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Projects struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RuntimeEnvironments struct {
	ID             pgtype.UUID        `json:"id"`
	Slug           string             `json:"slug"`
	ApiKey         string             `json:"api_key"`
	Type           string             `json:"type"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	OrgMemberID    pgtype.UUID        `json:"org_member_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Users struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
