// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package shared

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organizations, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Projects, error)
	CreateRuntimeEnvironment(ctx context.Context, arg CreateRuntimeEnvironmentParams) (RuntimeEnvironments, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	FindOrganizationBySlug(ctx context.Context, slug string) (Organizations, error)
	FindProjectBySlug(ctx context.Context, arg FindProjectBySlugParams) (Projects, error)
	FindRuntimeEnvironmentByAPIKey(ctx context.Context, apiKey string) (RuntimeEnvironments, error)
	FindRuntimeEnvironmentByPublicAPIKey(ctx context.Context, apiKey string) (RuntimeEnvironments, error)
	FindUserByEmail(ctx context.Context, email string) (Users, error)
	GetEnvironmentWithProjectAndOrg(ctx context.Context, id pgtype.UUID) (GetEnvironmentWithProjectAndOrgRow, error)
	// Organizations queries - trigger.dev Organization entity alignment
	GetOrganization(ctx context.Context, id pgtype.UUID) (Organizations, error)
	// Projects queries - trigger.dev Project entity alignment
	GetProject(ctx context.Context, id pgtype.UUID) (Projects, error)
	// Runtime Environments queries - trigger.dev RuntimeEnvironment alignment
	GetRuntimeEnvironment(ctx context.Context, id pgtype.UUID) (RuntimeEnvironments, error)
	// Users queries - trigger.dev User entity alignment
	GetUser(ctx context.Context, id pgtype.UUID) (Users, error)
	ListOrganizations(ctx context.Context) ([]Organizations, error)
	ListProjectsByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Projects, error)
	ListRuntimeEnvironmentsByProject(ctx context.Context, projectID pgtype.UUID) ([]RuntimeEnvironments, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organizations, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Projects, error)
	UpdateRuntimeEnvironment(ctx context.Context, arg UpdateRuntimeEnvironmentParams) (RuntimeEnvironments, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
