version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kongflow_dev
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: flow2025
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kong -d kongflow_dev']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
