// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package events

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountEventDispatchers(ctx context.Context, arg CountEventDispatchersParams) (int64, error)
	CountEventRecords(ctx context.Context, arg CountEventRecordsParams) (int64, error)
	// event_dispatchers.sql
	// Events Service - EventDispatcher 相关查询，对齐 trigger.dev 功能
	CreateEventDispatcher(ctx context.Context, arg CreateEventDispatcherParams) (EventDispatchers, error)
	// event_records.sql
	// Events Service - EventRecord 相关查询，对齐 trigger.dev 功能
	CreateEventRecord(ctx context.Context, arg CreateEventRecordParams) (EventRecords, error)
	DeleteEventDispatcher(ctx context.Context, id pgtype.UUID) error
	DeleteEventRecord(ctx context.Context, id pgtype.UUID) error
	// 查找匹配的事件调度器，对齐 trigger.dev DeliverEventService 逻辑
	FindEventDispatchers(ctx context.Context, arg FindEventDispatchersParams) ([]EventDispatchers, error)
	GetEventDispatcherByID(ctx context.Context, id pgtype.UUID) (EventDispatchers, error)
	GetEventRecordByEventID(ctx context.Context, arg GetEventRecordByEventIDParams) (EventRecords, error)
	GetEventRecordByID(ctx context.Context, id pgtype.UUID) (EventRecords, error)
	ListEventDispatchers(ctx context.Context, arg ListEventDispatchersParams) ([]EventDispatchers, error)
	ListEventRecords(ctx context.Context, arg ListEventRecordsParams) ([]EventRecords, error)
	// 获取待投递的事件记录，用于调度
	ListPendingEventRecords(ctx context.Context, arg ListPendingEventRecordsParams) ([]EventRecords, error)
	UpdateEventDispatcherEnabled(ctx context.Context, arg UpdateEventDispatcherEnabledParams) error
	UpdateEventRecordDeliveredAt(ctx context.Context, arg UpdateEventRecordDeliveredAtParams) error
	// Upsert 事件调度器，用于端点注册时更新调度器
	UpsertEventDispatcher(ctx context.Context, arg UpsertEventDispatcherParams) (EventDispatchers, error)
}

var _ Querier = (*Queries)(nil)
