// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package jobs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountJobsByProject(ctx context.Context, projectID pgtype.UUID) (int64, error)
	CountLaterJobVersions(ctx context.Context, arg CountLaterJobVersionsParams) (int64, error)
	// event_examples.sql
	// EventExample 事件示例相关查询
	CreateEventExample(ctx context.Context, arg CreateEventExampleParams) (EventExamples, error)
	// jobs.sql
	// Job 作业相关查询，对齐 trigger.dev 的 Job 操作
	CreateJob(ctx context.Context, arg CreateJobParams) (Jobs, error)
	// job_aliases.sql
	// JobAlias 作业别名相关查询
	CreateJobAlias(ctx context.Context, arg CreateJobAliasParams) (JobAliases, error)
	// job_queues.sql
	// JobQueue 作业队列相关查询
	CreateJobQueue(ctx context.Context, arg CreateJobQueueParams) (JobQueues, error)
	// job_versions.sql
	// JobVersion 作业版本相关查询
	CreateJobVersion(ctx context.Context, arg CreateJobVersionParams) (JobVersions, error)
	DecrementJobCount(ctx context.Context, id pgtype.UUID) (JobQueues, error)
	DeleteEventExample(ctx context.Context, id pgtype.UUID) error
	DeleteEventExamplesByJobVersion(ctx context.Context, jobVersionID pgtype.UUID) error
	DeleteEventExamplesNotInList(ctx context.Context, arg DeleteEventExamplesNotInListParams) error
	DeleteJob(ctx context.Context, id pgtype.UUID) error
	DeleteJobAlias(ctx context.Context, id pgtype.UUID) error
	DeleteJobAliasesByJob(ctx context.Context, jobID pgtype.UUID) error
	DeleteJobQueue(ctx context.Context, id pgtype.UUID) error
	DeleteJobVersion(ctx context.Context, id pgtype.UUID) error
	GetEventExampleByID(ctx context.Context, id pgtype.UUID) (EventExamples, error)
	GetEventExampleBySlug(ctx context.Context, arg GetEventExampleBySlugParams) (EventExamples, error)
	GetJobAliasByID(ctx context.Context, id pgtype.UUID) (JobAliases, error)
	GetJobAliasByName(ctx context.Context, arg GetJobAliasByNameParams) (JobAliases, error)
	GetJobByID(ctx context.Context, id pgtype.UUID) (Jobs, error)
	GetJobBySlug(ctx context.Context, arg GetJobBySlugParams) (Jobs, error)
	GetJobQueueByID(ctx context.Context, id pgtype.UUID) (JobQueues, error)
	GetJobQueueByName(ctx context.Context, arg GetJobQueueByNameParams) (JobQueues, error)
	GetJobVersionByID(ctx context.Context, id pgtype.UUID) (JobVersions, error)
	GetJobVersionByJobAndVersion(ctx context.Context, arg GetJobVersionByJobAndVersionParams) (JobVersions, error)
	GetLatestJobVersion(ctx context.Context, arg GetLatestJobVersionParams) (JobVersions, error)
	IncrementJobCount(ctx context.Context, id pgtype.UUID) (JobQueues, error)
	ListEventExamplesByJobVersion(ctx context.Context, jobVersionID pgtype.UUID) ([]EventExamples, error)
	ListJobAliasesByJob(ctx context.Context, arg ListJobAliasesByJobParams) ([]JobAliases, error)
	ListJobQueuesByEnvironment(ctx context.Context, arg ListJobQueuesByEnvironmentParams) ([]JobQueues, error)
	ListJobVersionsByJob(ctx context.Context, arg ListJobVersionsByJobParams) ([]JobVersions, error)
	ListJobsByOrganization(ctx context.Context, arg ListJobsByOrganizationParams) ([]Jobs, error)
	ListJobsByProject(ctx context.Context, arg ListJobsByProjectParams) ([]Jobs, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Jobs, error)
	UpdateJobQueueCounts(ctx context.Context, arg UpdateJobQueueCountsParams) (JobQueues, error)
	UpdateJobVersionProperties(ctx context.Context, arg UpdateJobVersionPropertiesParams) (JobVersions, error)
	UpsertEventExample(ctx context.Context, arg UpsertEventExampleParams) (EventExamples, error)
	UpsertJob(ctx context.Context, arg UpsertJobParams) (Jobs, error)
	UpsertJobAlias(ctx context.Context, arg UpsertJobAliasParams) (JobAliases, error)
	UpsertJobQueue(ctx context.Context, arg UpsertJobQueueParams) (JobQueues, error)
	UpsertJobVersion(ctx context.Context, arg UpsertJobVersionParams) (JobVersions, error)
}

var _ Querier = (*Queries)(nil)
