// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package apivote

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// API集成投票表，与trigger.dev模型100%对齐
type ApiIntegrationVote struct {
	ID string `json:"id"`
	// API标识符，如"github", "slack"等
	ApiIdentifier string `json:"apiIdentifier"`
	// 投票用户ID，关联用户表
	UserId string `json:"userId"`
	// 投票创建时间
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	// 投票更新时间
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}
