// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package apivote

import (
	"context"
)

type Querier interface {
	// ApiVote Service SQL Queries
	// 严格对齐 trigger.dev 的 ApiVoteService 功能
	// 对齐 trigger.dev: apiIntegrationVote.create()
	CreateApiVote(ctx context.Context, arg CreateApiVoteParams) (ApiIntegrationVote, error)
	// 删除用户对特定API的投票（可选功能）
	DeleteApiVoteByUserAndIdentifier(ctx context.Context, arg DeleteApiVoteByUserAndIdentifierParams) error
	// 查询用户对特定API的投票记录，用于防重复投票逻辑
	GetApiVoteByUserAndIdentifier(ctx context.Context, arg GetApiVoteByUserAndIdentifierParams) (ApiIntegrationVote, error)
}

var _ Querier = (*Queries)(nil)
