// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package endpoints

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (CreateEndpointRow, error)
	CreateEndpointIndex(ctx context.Context, arg CreateEndpointIndexParams) (CreateEndpointIndexRow, error)
	DeleteEndpoint(ctx context.Context, id pgtype.UUID) error
	DeleteEndpointIndex(ctx context.Context, id pgtype.UUID) error
	GetEndpointByID(ctx context.Context, id pgtype.UUID) (GetEndpointByIDRow, error)
	GetEndpointBySlug(ctx context.Context, arg GetEndpointBySlugParams) (GetEndpointBySlugRow, error)
	GetEndpointIndexByID(ctx context.Context, id pgtype.UUID) (GetEndpointIndexByIDRow, error)
	ListEndpointIndexes(ctx context.Context, endpointID pgtype.UUID) ([]ListEndpointIndexesRow, error)
	UpdateEndpointURL(ctx context.Context, arg UpdateEndpointURLParams) (UpdateEndpointURLRow, error)
	UpsertEndpoint(ctx context.Context, arg UpsertEndpointParams) (UpsertEndpointRow, error)
}

var _ Querier = (*Queries)(nil)
