// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package apiauth

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrganizationAccessTokens struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Token          string             `json:"token"`
	Name           string             `json:"name"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PersonalAccessTokens struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Token      string             `json:"token"`
	Name       string             `json:"name"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
