// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package secretstore

import (
	"time"
)

type SecretStore struct {
	Key       string    `json:"key"`
	Value     []byte    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
