// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package secretstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SecretStore struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
