// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secret_store.sql

package secretstore

import (
	"context"
)

const getSecretStore = `-- name: GetSecretStore :one
SELECT key, value, created_at, updated_at FROM secret_store WHERE key = $1
`

func (q *Queries) GetSecretStore(ctx context.Context, key string) (SecretStore, error) {
	row := q.db.QueryRow(ctx, getSecretStore, key)
	var i SecretStore
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSecretStore = `-- name: UpsertSecretStore :exec
INSERT INTO secret_store (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
`

type UpsertSecretStoreParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertSecretStore(ctx context.Context, arg UpsertSecretStoreParams) error {
	_, err := q.db.Exec(ctx, upsertSecretStore, arg.Key, arg.Value)
	return err
}
